baud_rate: 9600
com_port: COM16
invert_sliders: false
mute_mapping:
  "0": deej.mic
  "1": firefox.exe
noise_reduction: default
slider_mapping:
  "0":
  - chrome.exe
  - explorer.exe
  "1":
  - steam.exe
  - system
  "2":
  - explorer.exe
  "3":
  - steam.exe
  "4":
  - system
  "5": []
